; tfree0.g
; called when tool 0 is freed
;
; generated by RepRapFirmware Configuration Tool v3.1.4 on Fri Sep 11 2020 20:17:50 GMT+0800 (中國標準時間)
M208X-55Y0U53.7Z0S1
M208X62.5Y235U171.2 Z250 S0 
G60 S0
G91
G1 Z3 F6000
M83
G1 E-2 F6000
G1 E-6 F3000
G1 H1 X-250 F7000
G1 H1 U250 F7000
M579 U1
G54